### ISSUE TITLE
Debuffs not applying to monster status consistently

### ISSUE THREAD

**Issue by BHB88** [ronancpl/HeavenMS#445] opened 2019-04-07 02:03 UTC
It seems skills with FREEZE debuff isnt being applied consistently to monsters. 
Eg. I/L Mage Ice strike should freeze mobs at a 100% rate but is only happening around 60%

Skills affected:
I/L wizard - Cold beam
I/L mage - Ice strike
I/L archmage - blizzard
Sniper - blizzard
Marksman - Frost prey

Also this could be an issue with other statuses too as I've encountered Ranger's Silver hawk not stunning consistently.

**Comment by ronancpl** [comment] 2019-04-07 02:38
After testing those skills, couldn't notice any issue with them, ranging consistency. As far as the attack connects, there seems to be no issue around consistency. Are you able to reproduce those issues in a test session?

**Comment by BHB88** [comment] 2019-04-07 02:42
Yes, it seems to work perfectly upon a restart of the server. About one day of uptime, the consistency begins to fall off

**Comment by ronancpl** [comment] 2019-05-18 15:38
This may be intertwined with other runtime issues, that cannot be reliably reproduced by themselves... Closing this, for now.

**Closed by ronancpl** 2019-05-18 15:38 UTC
