### ISSUE TITLE
CPQ Some problems

### ISSUE THREAD

**Issue by Atoot** [ronancpl/HeavenMS#434] opened 2019-03-17 00:15 UTC
1.Functional Repeated Display of F1-F10。
2.Speed UP occasionally fails,Maybe other monster skills have the same problem.
3.CPQ1 room3-4.When the player dies. Not on the same battlefield after coming out.
4.CPQ is still in progress after the dissolution of the team.

**Comment by ronancpl** [comment] 2019-03-17 03:47
1. Confirmed issue.
2. Couldn't reproduce this case. It's known random diseases doesn't work as expected sometimes, though the same can't be said for protectors. Could you elaborate on this?
3. Confirmed issue, they would return to their respective team field successfully, but no the same area as before.
4. Confirmed issue.

**Comment by MedicOP** [comment] 2019-03-17 21:17
NPCs 2042000~2042009 are in Portuguese
NPC 2042001 still says the ore refinement stuff

**Comment by ronancpl** [comment] 2019-03-18 02:04
> NPCs 2042000~2042009, cpgchallenge1 cpqchallenge2 are in Portuguese

@MedicOP For the time being, there will have a server flag to disable CPQ contents. For anyone, a new pull request is most welcomed translating out the recently collaborated portuguese scripts into english.

> NPC 2042001 still says the ore refinement stuff

Alright, going to check this out. Thanks for reporting.

**Comment by ronancpl** [comment] 2019-03-26 19:32
Most of the issues have been cleared now. Closing this.

**Closed by ronancpl** 2019-03-26 19:32 UTC
