### ISSUE TITLE
MapleMap error I believe causes a crash to server

### ISSUE THREAD

**Issue by iAlpex** [ronancpl/HeavenMS#165] opened 2018-02-06 13:23 UTC
So I have been trying to figure out this error on my own for about a week and cannot figure out what is wrong with it. After this error if you log out of your character and try to log back in it sends you back to the Login Screen saying the Login ID is already online or the server is under maintenance. There are no other .bat errors except for the 1. 

`Error for player ; SyrupSauce on map ; 682000001 - account ; alexrrr
All: 31 00 08 00 21 6B 69 6C 6C 61 6C 6C 00
Now: 00
java.lang.NullPointerException
	at provider.MapleDataTool.getIntConvert(MapleDataTool.java:100)
	at server.MapleItemInformationProvider.isQuestItem(MapleItemInformationProvider.java:1232)
	at server.maps.MapleMap.sortDropEntries(MapleMap.java:567)
	at server.maps.MapleMap.dropFromMonster(MapleMap.java:666)
	at server.maps.MapleMap.killMonster(MapleMap.java:1142)
	at server.maps.MapleMap.killMonster(MapleMap.java:1063)
	at server.maps.MapleMap.damageMonster(MapleMap.java:1023)
	at client.command.Commands.executeSyrupCommandLv3(Commands.java:1891)
	at client.command.Commands.executeSyrupCommand(Commands.java:2657)
	at client.command.Commands.executeSyrupCommand(Commands.java:2672)
	at client.command.Commands.executeSyrupCommand(Commands.java:2672)
	at client.command.Commands.executeSyrupCommand(Commands.java:2672)
	at client.command.Commands.executeSyrupPlayerCommand(Commands.java:2680)
	at net.server.channel.handlers.GeneralChatHandler.handlePacket(GeneralChatHandler.java:54)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:159)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)`

**Comment by ronancpl** [comment] 2018-02-06 13:29
Most probably this error refers to Thanatos, this has happened because of an inconsistent itemid with a drop from it. Already solved this last commit. Please confirm this here.

**Comment by iAlpex** [comment] 2018-02-06 13:32
this is Headless HorseMan. but why does it crash the entire server even the ones that do not kill it? I am interested in learning.

**Comment by ronancpl** [comment] 2018-02-06 13:41
Headless HorseMan here works fine. It's proven as well there is no more inconsistent itemids on the SQL as well.

The problem is, the server is trying to drop items from HH, it will go through all itemids the mob drops. When testing an inexistent itemid on isQuestItem( ), it will throw an exception as the item data doesn't exist and will abruptly quit the processing handler (that still has relevant computing to do). Hence the server crash.

**Comment by resinate** [comment] 2018-02-09 12:35
under this "for (final MonsterDropEntry de : dropEntry) {"

add this block

if (de != null) {
} else {
                System.out.println("Error Item ID: " + de.itemId + " Does not exist.");
            }

**Comment by AznBoy00** [comment] 2018-02-09 14:07
@resinate why not simply
if(de==null)
System.out.println("Error Item ID: " + de.itemId + " Does not exist.");

**Comment by ronancpl** [comment] 2018-02-22 04:54
As noted above, isQuestItem was the cause of the issue when trying to check an inexistent itemid. The drop data on the SQL's here does not contain invalid itemids by now, also a check for nulls is being done on that function. Closing issue.

**Closed by ronancpl** 2018-02-22 04:54 UTC
